// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                pgtype.UUID      `json:"id"`
	Name              string           `json:"name"`
	Email             string           `json:"email"`
	Password          string           `json:"password"`
	Phone             pgtype.Text      `json:"phone"`
	PhoneCountryCode  pgtype.Text      `json:"phone_country_code"`
	ImagePath         pgtype.Text      `json:"image_path"`
	Role              string           `json:"role"`
	Address           pgtype.Text      `json:"address"`
	IsEmailVerified   bool             `json:"is_email_verified"`
	IsPhoneVerified   bool             `json:"is_phone_verified"`
	EmailOtp          pgtype.Text      `json:"email_otp"`
	EmailOtpExpiresAt pgtype.Timestamp `json:"email_otp_expires_at"`
	EmailOtpAttempts  int32            `json:"email_otp_attempts"`
	PhoneOtp          pgtype.Text      `json:"phone_otp"`
	PhoneOtpExpiresAt pgtype.Timestamp `json:"phone_otp_expires_at"`
	PhoneOtpAttempts  int32            `json:"phone_otp_attempts"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}
