// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearEmailOTP = `-- name: ClearEmailOTP :one
UPDATE users 
SET email_otp = NULL, email_otp_expires_at = NULL, email_otp_attempts = 0, is_email_verified = true, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, password, phone, phone_country_code, image_path, role, address, is_email_verified, is_phone_verified, email_otp, email_otp_expires_at, email_otp_attempts, phone_otp, phone_otp_expires_at, phone_otp_attempts, created_at, updated_at
`

func (q *Queries) ClearEmailOTP(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, clearEmailOTP, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.PhoneCountryCode,
		&i.ImagePath,
		&i.Role,
		&i.Address,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.EmailOtp,
		&i.EmailOtpExpiresAt,
		&i.EmailOtpAttempts,
		&i.PhoneOtp,
		&i.PhoneOtpExpiresAt,
		&i.PhoneOtpAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearPhoneOTP = `-- name: ClearPhoneOTP :one
UPDATE users 
SET phone_otp = NULL, phone_otp_expires_at = NULL, phone_otp_attempts = 0, is_phone_verified = true, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, password, phone, phone_country_code, image_path, role, address, is_email_verified, is_phone_verified, email_otp, email_otp_expires_at, email_otp_attempts, phone_otp, phone_otp_expires_at, phone_otp_attempts, created_at, updated_at
`

func (q *Queries) ClearPhoneOTP(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, clearPhoneOTP, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.PhoneCountryCode,
		&i.ImagePath,
		&i.Role,
		&i.Address,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.EmailOtp,
		&i.EmailOtpExpiresAt,
		&i.EmailOtpAttempts,
		&i.PhoneOtp,
		&i.PhoneOtpExpiresAt,
		&i.PhoneOtpAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password, role)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, password, phone, phone_country_code, image_path, role, address, is_email_verified, is_phone_verified, email_otp, email_otp_expires_at, email_otp_attempts, phone_otp, phone_otp_expires_at, phone_otp_attempts, created_at, updated_at
`

type CreateUserParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.PhoneCountryCode,
		&i.ImagePath,
		&i.Role,
		&i.Address,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.EmailOtp,
		&i.EmailOtpExpiresAt,
		&i.EmailOtpAttempts,
		&i.PhoneOtp,
		&i.PhoneOtpExpiresAt,
		&i.PhoneOtpAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, phone, phone_country_code, image_path, role, address, is_email_verified, is_phone_verified, email_otp, email_otp_expires_at, email_otp_attempts, phone_otp, phone_otp_expires_at, phone_otp_attempts, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.PhoneCountryCode,
		&i.ImagePath,
		&i.Role,
		&i.Address,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.EmailOtp,
		&i.EmailOtpExpiresAt,
		&i.EmailOtpAttempts,
		&i.PhoneOtp,
		&i.PhoneOtpExpiresAt,
		&i.PhoneOtpAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password, phone, phone_country_code, image_path, role, address, is_email_verified, is_phone_verified, email_otp, email_otp_expires_at, email_otp_attempts, phone_otp, phone_otp_expires_at, phone_otp_attempts, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.PhoneCountryCode,
		&i.ImagePath,
		&i.Role,
		&i.Address,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.EmailOtp,
		&i.EmailOtpExpiresAt,
		&i.EmailOtpAttempts,
		&i.PhoneOtp,
		&i.PhoneOtpExpiresAt,
		&i.PhoneOtpAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, name, email, password, phone, phone_country_code, image_path, role, address, is_email_verified, is_phone_verified, email_otp, email_otp_expires_at, email_otp_attempts, phone_otp, phone_otp_expires_at, phone_otp_attempts, created_at, updated_at FROM users WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.PhoneCountryCode,
		&i.ImagePath,
		&i.Role,
		&i.Address,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.EmailOtp,
		&i.EmailOtpExpiresAt,
		&i.EmailOtpAttempts,
		&i.PhoneOtp,
		&i.PhoneOtpExpiresAt,
		&i.PhoneOtpAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setEmailOTP = `-- name: SetEmailOTP :one
UPDATE users 
SET email_otp = $2, email_otp_expires_at = $3, email_otp_attempts = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, password, phone, phone_country_code, image_path, role, address, is_email_verified, is_phone_verified, email_otp, email_otp_expires_at, email_otp_attempts, phone_otp, phone_otp_expires_at, phone_otp_attempts, created_at, updated_at
`

type SetEmailOTPParams struct {
	ID                pgtype.UUID      `json:"id"`
	EmailOtp          pgtype.Text      `json:"email_otp"`
	EmailOtpExpiresAt pgtype.Timestamp `json:"email_otp_expires_at"`
	EmailOtpAttempts  int32            `json:"email_otp_attempts"`
}

func (q *Queries) SetEmailOTP(ctx context.Context, arg SetEmailOTPParams) (User, error) {
	row := q.db.QueryRow(ctx, setEmailOTP,
		arg.ID,
		arg.EmailOtp,
		arg.EmailOtpExpiresAt,
		arg.EmailOtpAttempts,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.PhoneCountryCode,
		&i.ImagePath,
		&i.Role,
		&i.Address,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.EmailOtp,
		&i.EmailOtpExpiresAt,
		&i.EmailOtpAttempts,
		&i.PhoneOtp,
		&i.PhoneOtpExpiresAt,
		&i.PhoneOtpAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPhoneOTP = `-- name: SetPhoneOTP :one
UPDATE users 
SET phone_otp = $2, phone_otp_expires_at = $3, phone_otp_attempts = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, password, phone, phone_country_code, image_path, role, address, is_email_verified, is_phone_verified, email_otp, email_otp_expires_at, email_otp_attempts, phone_otp, phone_otp_expires_at, phone_otp_attempts, created_at, updated_at
`

type SetPhoneOTPParams struct {
	ID                pgtype.UUID      `json:"id"`
	PhoneOtp          pgtype.Text      `json:"phone_otp"`
	PhoneOtpExpiresAt pgtype.Timestamp `json:"phone_otp_expires_at"`
	PhoneOtpAttempts  int32            `json:"phone_otp_attempts"`
}

func (q *Queries) SetPhoneOTP(ctx context.Context, arg SetPhoneOTPParams) (User, error) {
	row := q.db.QueryRow(ctx, setPhoneOTP,
		arg.ID,
		arg.PhoneOtp,
		arg.PhoneOtpExpiresAt,
		arg.PhoneOtpAttempts,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.PhoneCountryCode,
		&i.ImagePath,
		&i.Role,
		&i.Address,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.EmailOtp,
		&i.EmailOtpExpiresAt,
		&i.EmailOtpAttempts,
		&i.PhoneOtp,
		&i.PhoneOtpExpiresAt,
		&i.PhoneOtpAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users 
SET password = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, password, phone, phone_country_code, image_path, role, address, is_email_verified, is_phone_verified, email_otp, email_otp_expires_at, email_otp_attempts, phone_otp, phone_otp_expires_at, phone_otp_attempts, created_at, updated_at
`

type UpdatePasswordParams struct {
	ID       pgtype.UUID `json:"id"`
	Password string      `json:"password"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePassword, arg.ID, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.PhoneCountryCode,
		&i.ImagePath,
		&i.Role,
		&i.Address,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.EmailOtp,
		&i.EmailOtpExpiresAt,
		&i.EmailOtpAttempts,
		&i.PhoneOtp,
		&i.PhoneOtpExpiresAt,
		&i.PhoneOtpAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET name = $2, email = $3, phone = $4, phone_country_code = $5, image_path = $6, role = $7, address = $8, is_email_verified = $9, is_phone_verified = $10, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, password, phone, phone_country_code, image_path, role, address, is_email_verified, is_phone_verified, email_otp, email_otp_expires_at, email_otp_attempts, phone_otp, phone_otp_expires_at, phone_otp_attempts, created_at, updated_at
`

type UpdateUserParams struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	Email            string      `json:"email"`
	Phone            pgtype.Text `json:"phone"`
	PhoneCountryCode pgtype.Text `json:"phone_country_code"`
	ImagePath        pgtype.Text `json:"image_path"`
	Role             string      `json:"role"`
	Address          pgtype.Text `json:"address"`
	IsEmailVerified  bool        `json:"is_email_verified"`
	IsPhoneVerified  bool        `json:"is_phone_verified"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PhoneCountryCode,
		arg.ImagePath,
		arg.Role,
		arg.Address,
		arg.IsEmailVerified,
		arg.IsPhoneVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.PhoneCountryCode,
		&i.ImagePath,
		&i.Role,
		&i.Address,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.EmailOtp,
		&i.EmailOtpExpiresAt,
		&i.EmailOtpAttempts,
		&i.PhoneOtp,
		&i.PhoneOtpExpiresAt,
		&i.PhoneOtpAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users 
SET role = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, password, phone, phone_country_code, image_path, role, address, is_email_verified, is_phone_verified, email_otp, email_otp_expires_at, email_otp_attempts, phone_otp, phone_otp_expires_at, phone_otp_attempts, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.PhoneCountryCode,
		&i.ImagePath,
		&i.Role,
		&i.Address,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.EmailOtp,
		&i.EmailOtpExpiresAt,
		&i.EmailOtpAttempts,
		&i.PhoneOtp,
		&i.PhoneOtpExpiresAt,
		&i.PhoneOtpAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
